name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITTOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARTTOKEN }}
        with:
          args: >
              -Dsonar.organization=eweileen
              -Dsonar.projectKey=eweileen_SonarCloudCodeAnalyisis
              -Dsonar.python.coverage.reportPaths=coverage.xml
